import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { AseRobotGeneratedModule, AseRobotGeneratedSharedModule } from './generated/module.js';
import { AseRobotValidator } from './ase-robot-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type AseRobotAddedServices = {
    validation: {
        AseRobotValidator: AseRobotValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type AseRobotServices = LangiumServices & AseRobotAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const AseRobotModule: Module<AseRobotServices, PartialLangiumServices & AseRobotAddedServices> = {
    validation: {
        AseRobotValidator: () => new AseRobotValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createAseRobotServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    AseRobot: AseRobotServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        AseRobotGeneratedSharedModule
    );
    const AseRobot = inject(
        createDefaultModule({ shared }),
        AseRobotGeneratedModule,
        AseRobotModule
    );
    shared.ServiceRegistry.register(AseRobot);
    //registerValidationChecks(AseRobot);
    return { shared, AseRobot };
}
